export enum Genre {
    팝,
    키즈,
    애니메이션,
    보컬로이드,
    게임뮤직,
    버라이어티,
    클래식,
    남코오리지널,
}


export const genreColor: { [props:number]: string } = {
    0: "#42c0d2",
    1: "#ffc000",
    2: "#ff90d3",
    3: "#cdcfdf",
    4: "#cc8aea",
    5: "#1dc83b",
    6: "#c9c000",
    7: "#ff7027",
}

export enum Difficulty {
    졸업플러스,
    졸업,
    최상,
    상,
    중상,
    중,
    중하,
    하,
    최하,
    보류,
}

export enum ClearStatus {
    미클리어,
    클리어,
    풀콤,
    전량
}

// 난이도별 색상
export const difficultyColor: { [props: number]: string } = {
    0 : "#800380",
    1 : "#b70e52",
    2 : "#ed1c24",
    3 : "#fe7f28",
    4 : "#fec90e",
    5 : "#22b14c",
    6 : "#0fa238",
    7 : "#a349a4",
    8 : "#484848",
    9 : "#000000",
}

// 레벨별 난이도 리스트
export const DifficultyList: {[props: number]: Difficulty[]} = {
    10 : [Difficulty.졸업플러스, Difficulty.졸업, Difficulty.최상, Difficulty.상, Difficulty.중상, Difficulty.중, Difficulty.중하, Difficulty.하, Difficulty.최하, Difficulty.보류],
    9 : []
}

// Recoil State / Type

export type Song = {
    jpnTitle: string,
    korTitle?: string,
    info: {
        personal: boolean,  // 개인차 큼 - 빨간색
        hardFC: boolean     // 풀콤 어려움, - 보라색
        double: boolean     // 2인용,
        first: boolean      // 초견 어려움 - 초록색
    },
    genre: Genre[],         // 장르
    ura: boolean,           // 뒷보면 여부
    difficulty: Difficulty, // 난이도
    level: number,          // 레벨
    clear: ClearStatus,     // 현재 상태
    songNo: number,         // 남코 공식 곡 번호
}

/*
{
    jpnTitle: "",
    korTitle: "",
    info: {
        personal:false,  
        hardFC:false,   
        double:false,  
        first:false,  
    },
    genre: [],         
    ura:false,          
    difficulty: Difficulty.,
    clear: ClearStatus.미클리어,
    level: 10,       
},
*/

export const defaultRank: Song[] = [
    {
      jpnTitle: '彁',
      korTitle: '가',
      info: { personal: false, hardFC: false, double: false, first: true },
      genre: [ 7 ],
      ura: true,
      difficulty: 0,
      clear: 0,
      level: 10,
      songNo: 1206
    },
    {
      jpnTitle: '第六天魔王',
      korTitle: '제육천마왕',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 0,
      clear: 0,
      level: 10,
      songNo: 765
    },
    {
      jpnTitle: '憎悪と醜悪の花束',
      korTitle: '증오와 추악의 꽃다발',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 0,
      clear: 0,
      level: 10,
      songNo: 1043
    },
    {
      jpnTitle: 'poxei♦DOON',
      korTitle: '포세이돈',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 0,
      clear: 0,
      level: 10,
      songNo: 849
    },
    {
      jpnTitle: 'Infinite Rebellion',
      korTitle: '무한의 난',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 0,
      clear: 0,
      level: 10,
      songNo: 336
    },
    {
      jpnTitle: '神竜 ～Shinryu～',
      korTitle: '신룡',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 0,
      clear: 0,
      level: 10,
      songNo: 1129
    },
    {
      jpnTitle: '幽玄ノ乱',
      korTitle: '유현의 난',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 0,
      clear: 0,
      level: 10,
      songNo: 463
    },
    {
      jpnTitle: 'ドンカマ2000',
      korTitle: '동카마 2000',
      info: { personal: true, hardFC: false, double: false, first: true },
      genre: [ 7 ],
      ura: false,
      difficulty: 0,
      clear: 0,
      level: 10,
      songNo: 120
    },
    {
      jpnTitle: 'Central Dogma Pt.1',
      korTitle: 'Central Dogma Pt.1',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 0,
      clear: 0,
      level: 10,
      songNo: 954
    },
    {
      jpnTitle: 'Vixtory',
      korTitle: '빅스토리',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 0,
      clear: 0,
      level: 10,
      songNo: 960
    },
    {
      jpnTitle: 'ダンガンノーツ',
      korTitle: '탄환 노트',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 1,
      clear: 0,
      level: 10,
      songNo: 721
    },
    {
      jpnTitle: '双竜ノ乱',
      korTitle: '쌍룡의 난',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 1,
      clear: 0,
      level: 10,
      songNo: 393
    },
    {
      jpnTitle: '!!!カオスタイム!!!',
      korTitle: '카오스타임',
      info: { personal: true, hardFC: false, double: false, first: true },
      genre: [ 7 ],
      ura: false,
      difficulty: 1,
      clear: 0,
      level: 10,
      songNo: 518
    },
    {
      jpnTitle: 'The Future of the 太鼓ドラム',
      korTitle: '태고드럼의 미래',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 1,
      clear: 0,
      level: 10,
      songNo: 1072
    },
    {
      jpnTitle: '疾風怒濤',
      korTitle: '질풍노도',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 1,
      clear: 0,
      level: 10,
      songNo: 834
    },
    {
      jpnTitle: '狂瀾怒濤',
      korTitle: '광란노도',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 1,
      clear: 0,
      level: 10,
      songNo: 1122
    },
    {
      jpnTitle: 'モノクロボイス',
      korTitle: '모노크롬보이스',
      info: { personal: true, hardFC: false, double: false, first: true },
      genre: [ 7, 3 ],
      ura: true,
      difficulty: 1,
      clear: 0,
      level: 10,
      songNo: 868
    },
    {
      jpnTitle: 'チャーリー ダッシュ！',
      korTitle: '찰리 대시!',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 6, 7 ],
      ura: false,
      difficulty: 1,
      clear: 0,
      level: 10,
      songNo: 503
    },
    {
      jpnTitle: '≠MM',
      korTitle: '2000 아님',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 1,
      clear: 0,
      level: 10,
      songNo: 555
    },
    {
      jpnTitle: 'まださいたま2000',
      korTitle: '마다사이타마2000',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 1,
      clear: 0,
      level: 10,
      songNo: 627
    },
    {
      jpnTitle: 'Destination 2F29',
      korTitle: '데스티네이션 2F29',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 1,
      clear: 0,
      level: 10,
      songNo: 1172
    },
    {
      jpnTitle: 'ラ・モレーナ・クモナイ',
      korTitle: '라 모레나 쿠모나이',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 1,
      clear: 0,
      level: 10,
      songNo: 1196
    },
    {
      jpnTitle: 'Xa',
      korTitle: '이쿠사',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 1,
      clear: 0,
      level: 10,
      songNo: 451
    },
    {
      jpnTitle: 'Calamity Fortune',
      korTitle: '재앙운',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 5 ],
      ura: true,
      difficulty: 1,
      clear: 0,
      level: 10,
      songNo: 856
    },
    {
      jpnTitle: '業 -善なる神とこの世の悪について-',
      korTitle: '업 -선한 신과 이세상의 악에 관하여-',
      info: { personal: false, hardFC: true, double: false, first: false },
      genre: [ 4 ],
      ura: true,
      difficulty: 1,
      clear: 0,
      level: 10,
      songNo: 1080
    },
    {
      jpnTitle: '魑魅魍魎',
      korTitle: '이매망량',
      info: { personal: false, hardFC: true, double: false, first: true },
      genre: [ 7 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 1040
    },
    {
      jpnTitle: '星屑ストラック',
      korTitle: '별가루 스트럭',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 816
    },
    {
      jpnTitle: '続・〆ドレー2000',
      korTitle: '속-시메도레2000',
      info: { personal: true, hardFC: false, double: false, first: true },
      genre: [ 7 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 896
    },
    {
      jpnTitle: '万戈イム－一ノ十',
      korTitle: '성불2000',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 243
    },
    {
      jpnTitle: 'Coquette',
      korTitle: '요염한 여자',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 764
    },
    {
      jpnTitle: 'LΔchesis',
      korTitle: '라케시스',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 1145
    },
    {
      jpnTitle: '初音ミクの消失 -劇場版-',
      korTitle: '하츠네 미쿠의 소실 -극장판-',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7, 3 ],
      ura: true,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 283
    },
    {
      jpnTitle: 'そして勇者は眠りにつく',
      korTitle: '그리고 용사는 잠에 든다',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 1120
    },
    {
      jpnTitle: "UFO Swingin'",
      korTitle: "UFO Swingin'",
      info: { personal: true, hardFC: true, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 858
    },
    {
      jpnTitle: 'Taiko Drum Monster',
      korTitle: '태고 드럼 몬스터',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 700
    },
    {
      jpnTitle: 'Hurtling Boys',
      korTitle: '허틀링 보이즈',
      info: { personal: true, hardFC: true, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 186
    },
    {
      jpnTitle: '赤と白薔薇の魔女',
      korTitle: '적과 백장미의 마녀',
      info: { personal: false, hardFC: false, double: false, first: true },
      genre: [ 7 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 990
    },
    {
      jpnTitle: '森羅万象',
      korTitle: '삼라만상',
      info: { personal: true, hardFC: true, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 869
    },
    {
      jpnTitle: 'コネクトカラーズ',
      korTitle: '커넥트 컬러즈',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 850
    },
    {
      jpnTitle: '儚姫は原初に舞う',
      korTitle: '덧없는 공주는 원초에 춤을 춘다.',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 958
    },
    {
      jpnTitle: '懐中庭園を持つ少女',
      korTitle: '회중정원을 가진 소녀',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 702
    },
    {
      jpnTitle: 'わら得る2000',
      korTitle: '와라에루20000',
      info: { personal: false, hardFC: false, double: false, first: true },
      genre: [ 7 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 890
    },
    {
      jpnTitle: 'Behemoth',
      korTitle: '베헤모스',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 748
    },
    {
      jpnTitle: '冷凍庫CJ ～嗚呼面太鼓ブラザーズ～',
      korTitle: '냉동고CJ ~ 아멘 태고 브라더스 ~',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 593
    },
    {
      jpnTitle: 'ouroboros -twin stroke of the end-',
      korTitle: '',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 4 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 758
    },
    {
      jpnTitle: 'DEBSTEP!',
      korTitle: '뎁스텝!',
      info: { personal: true, hardFC: false, double: false, first: true },
      genre: [ 7 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 110
    },
    {
      jpnTitle: '束ね糸',
      korTitle: '묶은실',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 628
    },
    {
      jpnTitle: 'スーハー2000',
      korTitle: '스하2000',
      info: { personal: true, hardFC: false, double: false, first: true },
      genre: [ 7 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 401
    },
    {
      jpnTitle: 'χ談',
      korTitle: '괴담',
      info: { personal: true, hardFC: true, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 441
    },
    {
      jpnTitle: '彼は誰時の誘惑',
      korTitle: '새벽녘의 유혹',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 716
    },
    {
      jpnTitle: 'Challengers',
      korTitle: '챌린저스',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 1099
    },
    {
      jpnTitle: '氷竜 ~Kooryu~',
      korTitle: '빙룡',
      info: { personal: false, hardFC: true, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 866
    },
    {
      jpnTitle: '幕末維新譚',
      korTitle: '막말유신담',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 892
    },
    {
      jpnTitle: '絡繰廻廊',
      korTitle: '낙소회랑',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 955
    },
    {
      jpnTitle: 'カラフルボイス',
      korTitle: '컬러풀 보이스',
      info: { personal: false, hardFC: false, double: false, first: true },
      genre: [ 7, 3 ],
      ura: true,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 819
    },
    {
      jpnTitle: 'デッド・オア・ダイ',
      korTitle: 'Dead or Die',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 820
    },
    {
      jpnTitle: 'パンvsごはん！大決戦！ [달인]',
      korTitle: '빵vs밥! 대결전!',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 775
    },
    {
      jpnTitle: 'UNDEAD HEART',
      korTitle: 'UNDEAD HEART',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 690
    },
    {
      jpnTitle: 'Dreadnought',
      korTitle: 'Dreadnought',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 5 ],
      ura: true,
      difficulty: 2,
      clear: 0,
      level: 10,
      songNo: 845
    },
    {
      jpnTitle: '〆ドレー2000',
      korTitle: '시메도레2000',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 265
    },
    {
      jpnTitle: 'BLAZING VORTEX',
      korTitle: 'BLAZING VORTEX',
      info: { personal: true, hardFC: false, double: false, first: true },
      genre: [ 4 ],
      ura: true,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 553
    },
    {
      jpnTitle: '美しく忙しきドナウ',
      korTitle: '아름답고 바쁜 도나우',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 6, 7 ],
      ura: true,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 626
    },
    {
      jpnTitle: 'λ7708',
      korTitle: 'BOLLY',
      info: { personal: true, hardFC: false, double: false, first: true },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 778
    },
    {
      jpnTitle: 'カラフル',
      korTitle: '컬러풀',
      info: { personal: false, hardFC: true, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 777
    },
    {
      jpnTitle: "Player's High",
      korTitle: "Player's High",
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 1086
    },
    {
      jpnTitle: 'プチポチ',
      korTitle: '쁘띠 멍멍이',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 745
    },
    {
      jpnTitle: 'ラパスの虹',
      korTitle: '라파스의 무지개',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 972
    },
    {
      jpnTitle: 'まるくてはやくてすさまじいリズム',
      korTitle: '둥글고 빠르고 무시무시한 리듬',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 763
    },
    {
      jpnTitle: 'Aragami',
      korTitle: 'Aragami',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 5 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 1104
    },
    {
      jpnTitle: 'Xevel',
      korTitle: 'Xevel',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 4 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 757
    },
    {
      jpnTitle: 'Eternal Ring',
      korTitle: 'Eternel Ring',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 761
    },
    {
      jpnTitle: '青天の黎明',
      korTitle: '청천의 여명',
      info: { personal: true, hardFC: true, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 760
    },
    {
      jpnTitle: '其方、激昂',
      korTitle: '월광 소나타',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 6, 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 1108
    },
    {
      jpnTitle: 'アムピト♢リーテー',
      korTitle: '암피트♢리테',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 826
    },
    {
      jpnTitle: '螺旋周回軌道',
      korTitle: '나선주회궤도',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 959
    },
    {
      jpnTitle: '竜と黒炎の姫君',
      korTitle: '흑누나',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 15
    },
    {
      jpnTitle: 'パンvsごはん！大決戦！ [달인]',
      korTitle: '빵vs밥! 대결전!',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 775
    },
    {
      jpnTitle: '気焔万丈神楽',
      korTitle: '기염만장신락',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 851
    },
    {
      jpnTitle: '弧',
      korTitle: '호',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 1085
    },
    {
      jpnTitle: '†バチ!ムチ!?マッスルキングダム†',
      korTitle: '바찌!무찌!?머슬킹덤',
      info: { personal: false, hardFC: false, double: false, first: true },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 1041
    },
    {
      jpnTitle: 'たいこの2000',
      korTitle: '태고의2000',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 1066
    },
    {
      jpnTitle: 'Stick Trick Showtime!!',
      korTitle: 'Stick Trick Showtime!!',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 961
    },
    {
      jpnTitle: '弩蚊怒夏',
      korTitle: '도카도카',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7, 6 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 94
    },
    {
      jpnTitle: 'Central Dogma Pt.2',
      korTitle: 'Central Dogma Pt.2',
      info: { personal: false, hardFC: true, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 999
    },
    {
      jpnTitle: 'ナイトメア・サバイバー',
      korTitle: '나이트메어 서바이버',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 309
    },
    {
      jpnTitle: 'Rotter Tarmination',
      korTitle: 'Rotter Tarmination',
      info: { personal: false, hardFC: false, double: false, first: true },
      genre: [ 7 ],
      ura: true,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 402
    },
    {
      jpnTitle: 'Vixtory',
      korTitle: 'Vixtory',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 960
    },
    {
      jpnTitle: '燎原ノ舞',
      korTitle: '요원의 춤',
      info: { personal: false, hardFC: true, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 365
    },
    {
      jpnTitle: 'SUPERNOVA',
      korTitle: 'SUPERNOVA',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 1121
    },
    {
      jpnTitle: 'VERTeX',
      korTitle: 'VERTeX',
      info: { personal: true, hardFC: false, double: false, first: true },
      genre: [ 4 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 442
    },
    {
      jpnTitle: 'アンリミテッドゲームズ',
      korTitle: '언리미티드 게임즈',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 1048
    },
    {
      jpnTitle: 'The Future of the 太鼓ドラム',
      korTitle: '태고드럼의 미래',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 1072
    },
    {
      jpnTitle: "Don't Stop the Game",
      korTitle: "Don't Stop the Game",
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 818
    },
    {
      jpnTitle: "What's in the box?",
      korTitle: "What's in the box?",
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 835
    },
    {
      jpnTitle: 'FLOWER',
      korTitle: 'FLOWER',
      info: { personal: false, hardFC: true, double: false, first: false },
      genre: [ 4 ],
      ura: true,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 218
    },
    {
      jpnTitle: 'HARDCOREノ心得',
      korTitle: 'HARDCORE의 마음가짐',
      info: { personal: true, hardFC: true, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 685
    },
    {
      jpnTitle: 'GERBERA',
      korTitle: 'GERBERA',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 4 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 756
    },
    {
      jpnTitle: '或ル不和',
      korTitle: '알파',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 814
    },
    {
      jpnTitle: 'memoria ficta',
      korTitle: 'memoria ficta',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 905
    },
    {
      jpnTitle: 'Parousia',
      korTitle: 'Parousia',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 5 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 928
    },
    {
      jpnTitle: 'ドドドドドンだフル！',
      korTitle: '덩기덕 쿵더풀!',
      info: { personal: false, hardFC: false, double: false, first: true },
      genre: [ 7 ],
      ura: true,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 1201
    },
    {
      jpnTitle: '郢曲／暁闇',
      korTitle: '영곡/효암',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7, 5 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 495
    },
    {
      jpnTitle: '4+1のそれぞれの未来',
      korTitle: '4+1의 각자의 미래',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 3, 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 1012
    },
    {
      jpnTitle: 'ココロボ',
      korTitle: '코코로보',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 575
    },
    {
      jpnTitle: 'Gloria',
      korTitle: '글로리아',
      info: { personal: false, hardFC: true, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 594
    },
    {
      jpnTitle: '月読命',
      korTitle: '츠쿠요미',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 286
    },
    {
      jpnTitle: 'ON SAY GO SAY',
      korTitle: 'ON SAY GO SAY',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 1097
    },
    {
      jpnTitle: 'ARMAGEΔDON',
      korTitle: '아마겟돈',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 781
    },
    {
      jpnTitle: '秘ナルメジェドノ悲ナル憂鬱',
      korTitle: '메제드',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 723
    },
    {
      jpnTitle: '憎悪と醜悪の花束',
      korTitle: '증오와 추악의 꽃다발',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 1043
    },
    {
      jpnTitle: 'Goldfish City',
      korTitle: 'Goldfish City',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 3,
      clear: 0,
      level: 10,
      songNo: 833
    },
    {
      jpnTitle: '疾風怒濤',
      korTitle: '질풍노도',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 834
    },
    {
      jpnTitle: '極圏',
      korTitle: '극권',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 4 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 697
    },
    {
      jpnTitle: 'Scarlet Lance',
      korTitle: '스칼렛 랜스',
      info: { personal: false, hardFC: true, double: false, first: false },
      genre: [ 4 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 699
    },
    {
      jpnTitle: '怒槌',
      korTitle: '분노의 망치',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 4 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 698
    },
    {
      jpnTitle: '星河一天',
      korTitle: '성하일천',
      info: { personal: false, hardFC: true, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 971
    },
    {
      jpnTitle: 'メカデス。',
      korTitle: '메카데스',
      info: { personal: true, hardFC: false, double: false, first: true },
      genre: [ 7 ],
      ura: true,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 264
    },
    {
      jpnTitle: 'トイマチック☆パレード!!',
      korTitle: '토이매틱☆퍼레이드!!',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 737
    },
    {
      jpnTitle: 'Black Rose Apostle',
      korTitle: '흑장미사도',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 73
    },
    {
      jpnTitle: '天下統一録',
      korTitle: '천하통일록',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 786
    },
    {
      jpnTitle: 'アサガオ',
      korTitle: '아사가오',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 595
    },
    {
      jpnTitle: '8OROCHI',
      korTitle: '야마타노오로치',
      info: { personal: false, hardFC: true, double: false, first: true },
      genre: [ 7 ],
      ura: true,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 181
    },
    {
      jpnTitle: '天泣の律',
      korTitle: '천읍의 율',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 859
    },
    {
      jpnTitle: 'はたラク2000 ',
      korTitle: '하타라쿠2000',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 179
    },
    {
      jpnTitle: 'ひよこ鑑定士さん',
      korTitle: '병아리 감정사 씨',
      info: { personal: true, hardFC: true, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 982
    },
    {
      jpnTitle: 'もぺもぺ',
      korTitle: '모페모페',
      info: { personal: true, hardFC: false, double: false, first: true },
      genre: [ 5 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 843
    },
    {
      jpnTitle: 'Altale',
      korTitle: 'Altale',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 5 ],
      ura: true,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 804
    },
    {
      jpnTitle: 'Central Dogma Pt.1',
      korTitle: 'Central Dogma Pt.1',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 953
    },
    {
      jpnTitle: 'ex寅 Trap!!',
      korTitle: '엑스트라 트랩!!',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 1071
    },
    {
      jpnTitle: 'D絶対！SAMURAIインザレイン',
      korTitle: 'SAMIRAI 인 더 레인',
      info: { personal: false, hardFC: true, double: false, first: false },
      genre: [ 5 ],
      ura: true,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 735
    },
    {
      jpnTitle: 'Got more raves?',
      korTitle: 'Got more raves?',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 4 ],
      ura: true,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 164
    },
    {
      jpnTitle: 'Angel Halo',
      korTitle: 'Angel Halo',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 4 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 360
    },
    {
      jpnTitle: 'Fujin Rumble',
      korTitle: 'Fujin Rumble',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 4 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 148
    },
    {
      jpnTitle: 'Re : End of a Dream',
      korTitle: 'Re : End of a Dream',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 1197,
    },
    {
      jpnTitle: '白鳥の湖 ~still a duckling~',
      korTitle: '백조의 호수',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7, 6 ],
      ura: true,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 95
    },
    {
      jpnTitle: 'またさいたま2000',
      korTitle: '마타사이타마2000',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 355
    },
    {
      jpnTitle: 'きたさいたま2000',
      korTitle: '키타사이타마2000',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 338
    },
    {
      jpnTitle: 'テトラリュトモスフォビア',
      korTitle: '4박자 공포증',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 952
    },
    {
      jpnTitle: 'ANiMA',
      korTitle: 'ANiMA',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 4 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 934
    },
    {
      jpnTitle: 'LECIEL GLISSANDO',
      korTitle: 'LECIEL GLISSANDO',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 992
    },
    {
      jpnTitle: 'モノクロボイス',
      korTitle: '모노크롬 보이스',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7, 3 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 868
    },
    {
      jpnTitle: 'Calamity Fortune',
      korTitle: '재앙운',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 5 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 856
    },
    {
      jpnTitle: 'ヘイラ',
      korTitle: '헤이라',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 1146
    },
    {
      jpnTitle: 'ダンガンノーツ',
      korTitle: '탄환 노트',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 721
    },
    {
      jpnTitle: '秋竜 〜Shiuryu〜',
      korTitle: '추룡',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 519
    },
    {
      jpnTitle: '神竜 ～Shinryu～',
      korTitle: '신룡',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 1129
    },
    {
      jpnTitle: '超絶技巧系小女',
      korTitle: '초절기교계 소녀',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 577
    },
    {
      jpnTitle: 'Purple Rose Fusion',
      korTitle: 'Purple Rose Fusion',
      info: { personal: false, hardFC: true, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 335
    },
    {
      jpnTitle: 'ゴーゴー・キッチン',
      korTitle: '고고키친',
      info: { personal: true, hardFC: false, double: false, first: true },
      genre: [Genre.남코오리지널],
      ura: true,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 689
    },
    {
      jpnTitle: '人のお金で焼肉を食したい！',
      korTitle: '남의 돈으로 불고기를 먹고 싶어!',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 736
    },
    {
      jpnTitle: 'Silent Jealousy',
      korTitle: 'Silent Jealousy',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 0 ],
      ura: true,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 520
    },
    {
      jpnTitle: 'YOAKE',
      korTitle: '새벽',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 983
    },
    {
      jpnTitle: '共奏鼓祭',
      korTitle: '공주고제',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 1171
    },
    {
      jpnTitle: 'Honey Heartbeat ~10 Stars Mix~',
      korTitle: '',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 4, 2 ],
      ura: true,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 202
    },
    {
      jpnTitle: '哀 want U',
      korTitle: 'I want you',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 720
    },
    {
      jpnTitle: '愛と浄罪の森',
      korTitle: '사랑과 정죄의 숲',
      info: { personal: true, hardFC: false, double: false, first: true },
      genre: [ 7 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 722
    },
    {
      jpnTitle: 'チルノのパーフェクトさんすう教室 (9)',
      korTitle: '치르노의 산수교실 9주년 버전',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 5 ],
      ura: true,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 681
    },
    {
      jpnTitle: 'Spectral Rider',
      korTitle: 'Spectral Rider',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 4,
      clear: 0,
      level: 10,
      songNo: 1068
    },
    {
      jpnTitle: 'Doom Noiz',
      korTitle: 'Doom Noiz',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 4 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 121
    },
    {
      jpnTitle: '彁',
      korTitle: '가',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 993
    },
    {
      jpnTitle: 'ハンロック',
      korTitle: '헝록',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 6, 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 774
    },
    {
      jpnTitle: '天照',
      korTitle: '아마테라스',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 630
    },
    {
      jpnTitle: '刻竜 ～Kokuryu～',
      korTitle: '각룡',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 1042
    },
    {
      jpnTitle: 'ドドンガド～ン',
      korTitle: '도동가동',
      info: { personal: true, hardFC: false, double: false, first: true },
      genre: [ 7 ],
      ura: true,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 266
    },
    {
      jpnTitle: 'ゴーストマスク',
      korTitle: '고스트 마스크',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 3, 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 570
    },
    {
      jpnTitle: 'にゃーにゃーにゃー',
      korTitle: '냐~냐~냐~',
      info: { personal: false, hardFC: true, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 860
    },
    {
      jpnTitle: "Toon Town's Toys Tune",
      korTitle: "Toon Town's Toys Tune",
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 762
    },
    {
      jpnTitle: 'Taiko Drum Monster',
      korTitle: 'Taiko Drum Monster',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 700
    },
    {
      jpnTitle: 'Calculator',
      korTitle: 'Calculator',
      info: { personal: true, hardFC: true, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 68
    },
    {
      jpnTitle: '頂',
      korTitle: '이타다키',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 784
    },
    {
      jpnTitle: '紫煌ノ乱 ',
      korTitle: '자황의 난',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 477
    },
    {
      jpnTitle: '重金属フューギティブ',
      korTitle: '중금속 퓨기티브',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 3, 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 171
    },
    {
      jpnTitle: 'MagiCatz',
      korTitle: 'MagiCatz',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 4 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 935
    },
    {
      jpnTitle: 'aleph-0',
      korTitle: 'aleph-0',
      info: { personal: true, hardFC: false, double: false, first: true },
      genre: [ 5 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 1134,
    },
    {
      jpnTitle: '蒼の旋律',
      korTitle: '창의 선율',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 45
    },
    {
      jpnTitle: 'マツヨイナイトバグ',
      korTitle: '마츠요이 나이트버그',
      info: { personal: false, hardFC: false, double: false, first: true },
      genre: [ 5 ],
      ura: true,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 1035
    },
    {
      jpnTitle: '練習曲 Op.10-4',
      korTitle: '연습곡 Op.10-4',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 6, 7 ],
      ura: true,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 80,
    },
    {
      jpnTitle: 'Garakuta Doll Play',
      korTitle: 'Garakuta Doll Play',
      info: { personal: true, hardFC: true, double: false, first: false },
      genre: [ 4 ],
      ura: true,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 154,
    },
    {
      jpnTitle: 'ウルトラマンX',
      korTitle: '울트라맨X',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 1 ],
      ura: true,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 493
    },
    {
      jpnTitle: 'そつおめしき',
      korTitle: '졸업축하식',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 388
    },
    {
      jpnTitle: 'そつおめしき2ばん',
      korTitle: '졸업축하식 2절',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 677
    },
    {
      jpnTitle: 'BATTLE NO.1 [달인]',
      korTitle: 'BATTLE NO.1',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 5 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 1037
    },
    {
      jpnTitle: 'あの日出会えたキセキ',
      korTitle: '그날 만난 기적',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 798
    },
    {
      jpnTitle: 'Hello, Mr.JOKER',
      korTitle: 'Hello, Mr.JOKER',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 1050
    },
    {
      jpnTitle: 'No Gravity',
      korTitle: 'No Gravity',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 673
    },
    {
      jpnTitle: 'うちゅうひこうし冒険譚',
      korTitle: '우주비행사 모험담',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 867
    },
    {
      jpnTitle: 'アキバ20XX',
      korTitle: '아키바20XX',
      info: { personal: false, hardFC: false, double: false, first: true },
      genre: [ 5 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 1173
    },
    {
      jpnTitle: '夏祭り / ジッタリン・ジン',
      korTitle: "여름 축제/JITTERIN'JINN",
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 0 ],
      ura: true,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 1027
    },
    {
      jpnTitle: 'Evidence of evil',
      korTitle: 'Evidence of evil',
      info: { personal: false, hardFC: true, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 136
    },
    {
      jpnTitle: '最終鬼畜妹フランドール・Ｓ',
      korTitle: '최종귀축 여동생 플랑드르-S',
      info: { personal: true, hardFC: true, double: false, first: false },
      genre: [ 5 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 538,
    },
    {
      jpnTitle: 'ミュージック・リボルバー',
      korTitle: '뮤직 리볼버',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 272
    },
    {
      jpnTitle: '鼓舞曲「閻魔」',
      korTitle: '고무곡「염마」',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 1039
    },
    {
      jpnTitle: 'wonderful ROUTINE',
      korTitle: 'wonderful ROUTINE',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 940
    },
    {
      jpnTitle: 'Agent Hustle & Dr. Hassle',
      korTitle: 'Agent Hustle & Dr. Hassle',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 1067,
    },
    {
      jpnTitle: 'ペットショップ大戦',
      korTitle: '펫숍 대전',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 906
    },
    {
      jpnTitle: 'God Ray',
      korTitle: 'God Ray',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 4 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 427
    },
    {
      jpnTitle: 'ギガンティックO.T.N',
      korTitle: '기간틱 O.T.N',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 3 ],
      ura: true,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 537
    },
    {
      jpnTitle: 'Abyss of hell',
      korTitle: 'Abyss of hell',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 4 ],
      ura: true,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 504
    },
    {
      jpnTitle: 'ラヴ♡スパイス♡ライクユー!!!',
      korTitle: '러브♡스파이스♡라이크유!!!',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 815
    },
    {
      jpnTitle: 'FREEDOM DiVE',
      korTitle: 'FREEDOM DiVE',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 5 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 803,
    },
    {
      jpnTitle: '濃紅',
      korTitle: '농홍',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 450
    },
    {
      jpnTitle: 'キューティー☆デモニック☆魔人エモ!!',
      korTitle: '큐티☆데모닉☆마인에모!!',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 846
    },
    {
      jpnTitle: 'ノるどん2000',
      korTitle: '노루동2000',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 499
    },
    {
      jpnTitle: '晨星ト鵺',
      korTitle: '신성과 누에',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 1049
    },
    {
      jpnTitle: 'セイクリッド ルイン',
      korTitle: '세이크리드 루인',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 400
    },
    {
      jpnTitle: 'ピコピコ ルイン',
      korTitle: '피코피코 루인',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 399
    },
    {
      jpnTitle: 'カラ鞠の花',
      korTitle: '컬러공의 꽃',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7, 3 ],
      ura: false,
      difficulty: 5,
      clear: 0,
      level: 10,
      songNo: 220
    },
    {
      jpnTitle: 'Surf Zapping',
      korTitle: 'Surf Zapping',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 4 ],
      ura: false,
      difficulty: 6,
      clear: 0,
      level: 10,
      songNo: 759
    },
    {
      jpnTitle: 'Dogbite',
      korTitle: 'Dogbite',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 5 ],
      ura: false,
      difficulty: 6,
      clear: 0,
      level: 10,
      songNo: 927
    },
    {
      jpnTitle: 'SUPERNOVA',
      korTitle: 'SUPERNOVA',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 6,
      clear: 0,
      level: 10,
      songNo: 1121
    },
    {
      jpnTitle: 'Diving Drive',
      korTitle: 'Diving Drive',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 6,
      clear: 0,
      level: 10,
      songNo: 977
    },
    {
      jpnTitle: 'VIVIVIVID',
      korTitle: 'VIVIVIVID',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 6,
      clear: 0,
      level: 10,
      songNo: 980
    },
    {
      jpnTitle: 'ゴッドソング',
      korTitle: '갓송',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 0 ],
      ura: true,
      difficulty: 6,
      clear: 0,
      level: 10,
      songNo: 920
    },
    {
      jpnTitle: "D's Adventure Note",
      korTitle: "D's Adventure Note",
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 6,
      clear: 0,
      level: 10,
      songNo: 128,
    },
    {
      jpnTitle: 'SstTAarR*',
      korTitle: 'SstTAarR*',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 3, 7 ],
      ura: false,
      difficulty: 6,
      clear: 0,
      level: 10,
      songNo: 574
    },
    {
      jpnTitle: 'Caribbean Knight',
      korTitle: '캐리비안 나이트',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 6,
      clear: 0,
      level: 10,
      songNo: 878
    },
    {
      jpnTitle: '8OROCHI',
      korTitle: '야마타노오로치',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 6,
      clear: 0,
      level: 10,
      songNo: 181
    },
    {
      jpnTitle: '朱の旋律',
      korTitle: '주의 선율',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 6,
      clear: 0,
      level: 10,
      songNo: 513
    },
    {
      jpnTitle: '承認欲Q',
      korTitle: '승인욕Q',
      info: { personal: false, hardFC: true, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 6,
      clear: 0,
      level: 10,
      songNo: 571
    },
    {
      jpnTitle: 'Libera Ray',
      korTitle: 'Libera Ray',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 4 ],
      ura: false,
      difficulty: 6,
      clear: 0,
      level: 10,
      songNo: 1106
    },
    {
      jpnTitle: 'クラポルポルスカ',
      korTitle: '크라폴 폴스카',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7, 6 ],
      ura: false,
      difficulty: 6,
      clear: 0,
      level: 10,
      songNo: 943
    },
    {
      jpnTitle: 'Ignis Danse',
      korTitle: 'Ignis Danse',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 6,
      clear: 0,
      level: 10,
      songNo: 194
    },
    {
      jpnTitle: '零の交響曲',
      korTitle: '영의 교향곡',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 6,
      clear: 0,
      level: 10,
      songNo: 938
    },
    {
      jpnTitle: 'X-DAY2000',
      korTitle: 'X-DAY2000',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 6,
      clear: 0,
      level: 10,
      songNo: 452
    },
    {
      jpnTitle: 'メタナイトの逆襲メドレー',
      korTitle: '메타나이트의 역습 메들리',
      info: { personal: false, hardFC: true, double: false, first: false },
      genre: [ 4, 1 ],
      ura: true,
      difficulty: 6,
      clear: 0,
      level: 10,
      songNo: 222
    },
    {
      jpnTitle: '儚姫は原初に舞う',
      korTitle: '덧없는 공주는 원초에 춤을 춘다.',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 6,
      clear: 0,
      level: 10,
      songNo: 958
    },
    {
      jpnTitle: '十露盤2000',
      korTitle: '십노반2000',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 6,
      clear: 0,
      level: 10,
      songNo: 392
    },
    {
      jpnTitle: "OK I'm blue rat",
      korTitle: "OK I'm blue rat",
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 6,
      clear: 0,
      level: 10,
      songNo: 714,
    },
    {
      jpnTitle: 'てんぢく2000',
      korTitle: '텐지쿠2000',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 6,
      clear: 0,
      level: 10,
      songNo: 1
    },
    {
      jpnTitle: 'EkiBEN2000',
      korTitle: 'EkiBEN2000',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 131
    },
    {
      jpnTitle: 'Black Rose Apostle',
      korTitle: 'Black Rose Apostle',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 73
    },
    {
      jpnTitle: 'Illusion Flare',
      korTitle: 'Illusion Flare',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 1147
    },
    {
      jpnTitle: 'タイコタイム',
      korTitle: '태고 타임',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 425
    },
    {
      jpnTitle: 'スーパーD&D',
      korTitle: '슈퍼 D&D',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 5 ],
      ura: false,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 734,
    },
    {
      jpnTitle: 'チルノのパーフェクトさんすう教室',
      korTitle: '치르노의 퍼펙트 산수교실',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 5 ],
      ura: true,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 414
    },
    {
      jpnTitle: '星屑ストラック',
      korTitle: '별무리 스트럭',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 816
    },
    {
      jpnTitle: 'Clotho クロートー',
      korTitle: '클로토',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 779
    },
    {
      jpnTitle: 'ヒバナ',
      korTitle: 'HIBANA',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 3 ],
      ura: true,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 730
    },
    {
      jpnTitle: 'よーいドン！',
      korTitle: '준비 땅!',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 724
    },
    {
      jpnTitle: 'Doppelgangers',
      korTitle: '도플갱어',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7, 5 ],
      ura: true,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 1133
    },
    {
      jpnTitle: 'タイコロール',
      korTitle: '태고 롤',
      info: { personal: true, hardFC: true, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 879
    },
    {
      jpnTitle: 'SORA-VII シグナスウォール',
      korTitle: '소라-VII 시그너스 월',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 719
    },
    {
      jpnTitle: 'INSPION',
      korTitle: 'INSPION',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 5 ],
      ura: false,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 456
    },
    {
      jpnTitle: 'メタルホーク BGM1',
      korTitle: '메탈호크 BGM1',
      info: { personal: true, hardFC: true, double: false, first: false },
      genre: [ 4 ],
      ura: false,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 269
    },
    {
      jpnTitle: 'パンvsごはん！大決戦！[보통]',
      korTitle: '빵vs밥! 대결전!',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 775
    },
    {
      jpnTitle: 'パンvsごはん！大決戦！[보통]',
      korTitle: '빵vs밥! 대결전!',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 775
    },
    {
      jpnTitle: 'さちさちにしてあげる♪',
      korTitle: '사치사치하게 해줄게♪',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 3, 0 ],
      ura: true,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 118
    },
    {
      jpnTitle: 'ウィーアー!',
      korTitle: '위어!',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 2, 1 ],
      ura: true,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 1022
    },
    {
      jpnTitle: 'R.I.',
      korTitle: 'R.I.',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 686
    },
    {
      jpnTitle: '三瀬川乱舞',
      korTitle: '삼도천난무',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 448
    },
    {
      jpnTitle: '鼓立あおはる学園校歌',
      korTitle: '고립 아오하루 학원 교가',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 1185
    },
    {
      jpnTitle: 'Venomous',
      korTitle: 'Venomous',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 4 ],
      ura: false,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 361
    },
    {
      jpnTitle: 'KAGEKIYO',
      korTitle: 'KAGEKIYO',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 4 ],
      ura: true,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 156
    },
    {
      jpnTitle: '夜桜謝肉祭',
      korTitle: '야앵사육제',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: true,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 60
    },
    {
      jpnTitle: '六華の舞',
      korTitle: '육화의 춤',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 1154
    },
    {
      jpnTitle: "waitin' for u",
      korTitle: "waitin' for u",
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 5 ],
      ura: false,
      difficulty: 7,
      clear: 0,
      level: 10,
      songNo: 929
    },
    {
      jpnTitle: '拝啓ドッペルゲンガー',
      korTitle: '친애하는 도플갱어에게',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 3 ],
      ura: false,
      difficulty: 8,
      clear: 0,
      level: 10,
      songNo: 695
    },
    {
      jpnTitle: '旋風ノ舞【天】',
      korTitle: '선풍의 춤 [천]',
      info: { personal: true, hardFC: false, double: true, first: true },
      genre: [ 7 ],
      ura: true,
      difficulty: 8,
      clear: 0,
      level: 10,
      songNo: 371
    },
    {
      jpnTitle: '旋風ノ舞【天】',
      korTitle: '선풍의 춤 [천]',
      info: { personal: true, hardFC: false, double: false, first: true },
      genre: [ 7 ],
      ura: false,
      difficulty: 8,
      clear: 0,
      level: 10,
      songNo: 371
    },
    {
      jpnTitle: 'mint tears',
      korTitle: 'mint tears',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 8,
      clear: 0,
      level: 10,
      songNo: 288
    },
    {
      jpnTitle: 'Blessed Bouquet Buskers',
      korTitle: '축복받은 꽃다발 연주자들',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 8,
      clear: 0,
      level: 10,
      songNo: 715
    },
    {
      jpnTitle: 'VICTORIA',
      korTitle: 'VICTORIA',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 8,
      clear: 0,
      level: 10,
      songNo: 641
    },
    {
      jpnTitle: '詩謳兎揺蕩兎',
      korTitle: '노래하는 토끼',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 8,
      clear: 0,
      level: 10,
      songNo: 1158
    },
    {
      jpnTitle: '須佐之男',
      korTitle: '스사노오',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 8,
      clear: 0,
      level: 10,
      songNo: 635
    },
    {
      jpnTitle: 'Kamikaze Remix',
      korTitle: 'Kamikaze Remix',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 4 ],
      ura: false,
      difficulty: 8,
      clear: 0,
      level: 10,
      songNo: 363
    },
    {
      jpnTitle: 'タベルナ2000',
      korTitle: '타베루나2000',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 7 ],
      ura: false,
      difficulty: 8,
      clear: 0,
      level: 10,
      songNo: 404
    },
    {
      jpnTitle: 'オーブの祈り',
      korTitle: '오브의 기도',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 1 ],
      ura: false,
      difficulty: 8,
      clear: 0,
      level: 10,
      songNo: 621
    },
    {
      jpnTitle: '乱数調整のリバースシンデレラ',
      korTitle: '난수조정의 신데렐라',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 0 ],
      ura: false,
      difficulty: 8,
      clear: 0,
      level: 10,
      songNo: 1020
    },
    {
      jpnTitle: 'ゲゲゲの鬼太郎',
      korTitle: '게게게의 기타로',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 2, 1 ],
      ura: true,
      difficulty: 8,
      clear: 0,
      level: 10,
      songNo: 831
    },
    {
      jpnTitle: 'あなたとトゥラッタッタ♪',
      korTitle: '당신과 투랏탓타♪',
      info: { personal: true, hardFC: false, double: false, first: false },
      genre: [ 0 ],
      ura: true,
      difficulty: 8,
      clear: 0,
      level: 10,
      songNo: 811
    },
    {
      jpnTitle: 'ネクロファンタジア',
      korTitle: '네크로판타지아',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 5 ],
      ura: false,
      difficulty: 8,
      clear: 0,
      level: 10,
      songNo: 421
    },
    {
      jpnTitle: 'BATTLE NO.1 [현인]',
      korTitle: 'BATTLE NO.1',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 5 ],
      ura: false,
      difficulty: 8,
      clear: 0,
      level: 10,
      songNo: 1037
    },
    {
      jpnTitle: 'BATTLE NO.1 [보통]',
      korTitle: 'BATTLE NO.1',
      info: { personal: false, hardFC: false, double: false, first: false },
      genre: [ 5 ],
      ura: false,
      difficulty: 8,
      clear: 0,
      level: 10,
      songNo: 1037
    }
  ]
  